spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: '*'
            allowedHeaders: '*'      
            
     # add microservice routes here
      routes:
      - id: users
        uri: lb://users
        predicates:
        - Path=/auth/**,/admin/**,/users/**
      # No filters       
        
      - id: languages
        uri: lb://languages
        predicates:
        - Path=/languages/**
        filters:
        - LingoApiAuthFilter

      - id: quizzes
        uri: lb://quizzes
        predicates:
        - Path=/quizzes/**
        filters:
        - LingoApiAuthFilter
                        
       # testing node microservices
      - id: node-service
        uri: lb://node-service
        predicates:
        - Path=/node-service/**
server: 
  port: 8765

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost
