spring:
  application:
    name: api-gateway
  cloud:
    gateway:
     # add microservice routes here
      routes:
      - id: users
        uri: lb://users
        predicates:
        - Path=/auth/**
      # No filters       
        
      - id: languages
        uri: lb://languages
        predicates:
        - Path=/languages/**
        filters:
        - LingoAuthFilter

      - id: quizzes
        uri: lb://quizzes
        predicates:
        - Path=/quizzes/**
        filters:
        - LingoAuthFilter
                        
       # testing node microservices
      - id: node-service
        uri: lb://node-service
        predicates:
        - Path=/node-service/**
server: 
  port: 8765

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost
